version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: update apt
          command: apt update -y
      - run:
          name: install make/gcc
          command: apt install -y make gcc
      - run: make CC=gcc
      - run: bin/jpeg lena.bmp lena.jpg